apiVersion: v1
#Menentukan versi API
kind: Secret
#Menentukan jenis deployment
metadata:
  name: mongodb-secret
#Menambahkan informasi metadata berupa nama
type: Opaque
#Menentukan jenis secret
data:
  MONGO_ROOT_USERNAME: YWRtaW4=
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA==
#Isi dari data secret dalam base64
