apiVersion: v1
#Menentukan Versi API
kind: PersistentVolume
#Menentukan jenis deployment
metadata:
    name: mongodb-pv2
    labels:
      type: local
#Menentukan metadata nama dan label
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data2
 #spesifikasi penyimpanan pv
--- 
apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc2
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
 #mendelegasikan pvc claim
