apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
        selector: mongodb
    spec:
      containers:
      - name: mongodb-cnt
        image: mongo:4.0.8
        env:
          - name: MONGO_INITDB_ROOT_USERNAME_FILE
            value: /etc/mongo-credentials/MONGO_ROOT_USERNAME
          - name: MONGO_INITDB_ROOT_PASSWORD_FILE
            value: /etc/mongo-credentials/MONGO_ROOT_PASSWORD
        volumeMounts:
        - name: mongodb-secret
          mountPath: /etc/mongo-credentials
        - name: mongodb-configmap
          mountPath: /config
        - name: mongodb-data
          mountPath: /data/db
      volumes:
      - name: mongodb-secret
        secret:
          secretName: mongodb-secret
          items:
          - key: MONGO_ROOT_USERNAME
            path: MONGO_ROOT_USERNAME
          - key: MONGO_ROOT_PASSWORD
            path: MONGO_ROOT_PASSWORD
      - name: mongodb-configmap
        configMap:
          name: mongodb-configmap
          items:
          - key: mongo.conf
            path: mongo.conf
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: mongodb-pvc2
