apiVersion: v1
kind: PersistentVolume
metadata:
    name: mongodb-pv2
    labels:
      type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data2
--- 
apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc2
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
