version: "3.7" 
# Menggunakan Docker Compose versi 2 atau lebih

services: 
# menambahkan service
  item-db: 
  # tambahkan service item-db
    image: docker.io/mongo:3 
    # image berasal dari docker hub
    volumes: 
    # delegasi volumes
      - app-db:/data/db 
      # volume menggunakan app-db
  item-app: 
  # tambahkan service item-app
    depends_on: 
    # memastikan item-app hanya berjalan setelah item-db diluncurkan
      - item-db  
    image: ghcr.io/coopmech/item-app:v1 
    # image berasal dari github package
    ports: 
    # Melakukan port mapping agar dapat diakses dari port 80 di host
      - 8080:80
    restart: always 
    # penerapan restart policy
volumes: 
# Memiliki satu buah volume bernama app-db
  app-db: