version: 2.1

executors:
  docker:
    docker:
      - image: docker:stable

jobs:
  build:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker
      # Lint the Dockerfile
      - run:
          name: authentication
          command: export PASSWORD_DOCKER_HUB=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 && echo $PASSWORD_DOCKER_HUB | docker login ghcr.io --username phanatic --password-stdin
      - run:
          name: lint-dockerfile
          command: docker run --rm --interactive hadolint/hadolint < Dockerfile
      - run:
          name: test-app
          command: apk add --update --no-cache vim git make musl-dev go curl && go test -v -short --count=1 $(go list ./...)
      - run:
          name: build-app-karsajobs
          command: docker build -t ghcr.io/coopmech/karsajobs:v1 . && docker push ghcr.io/coopmech/karsajobs:v1

workflows:
  version: 2
  build-lint:
    jobs:
      - build
