version: 2.1

executors:
  docker:
    docker:
      - image: docker:stable

jobs:
  build:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker
      # Lint the Dockerfile
      - run:
          name: lint-dockerfile
          command: git clone https://github.com/coopmech/a433-microservices -b karsajobs && cd a433-microservices && docker run --rm --interactive hadolint/hadolint < https://github.com/coopmech/a433-microservices/Dockerfile
      - run:
          name: test-app
          command: go test -v -short --count=1 $(go list ./...)
      - run:
          name: build-app-karsajobs
          command: export PASSWORD_REPO=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 && echo $PASSWORD_REPO | docker login ghcr.io --username coopmech --password-stdin && docker push ghcr.io/coopmech/karsajobs:v1

workflows:
  version: 2
  build-lint:
    jobs:
      - build
